### ISSUE TITLE
launcher not working 

### ISSUE THREAD

**Issue by HYZz3N** [Carberra/updated-discord.py-tutorial#5]
Hi there 
when I start the bot with a launcher.py it shows 2 errors
##
**Traceback (most recent call last):
  File "X:/XPython/discordbot-py/launcher.py", line 1, in <module>
    from lib.bot import bot
  File "X:\X\Python\discordbot-py\lib\bot\__init__.py", line 5, in <module>
    from apscheduler.schedulers.asyncio import AsyncIOScheduler
ModuleNotFoundError: No module named 'apscheduler'**
##

Thank you!

**Comment by BluTenGaming** [comment]
**Did you install apscheduler?**

**Comment by HYZz3N** [comment]
> **Did you install apscheduler?**

yes I've installed everything I need

**Comment by UnspankableGoose** [comment]
Are you sure? That error(specifically) only appears if the package is not installed. To be sure, open IDLE or another interactive python environment on the version of python your editor is running, and try to import apscheduler from that terminal. If it works, then we have more information knowing it's the editors problem, and not some python "path" problems.

**Comment by parafoxia** [comment]
Please ask your question in the support server; the GitHub repo should not be used as a support channel.
